name: update website

on:
  push:
    branches:
    - main
      path:
      - '/frontend/dist'
    
    
    steps:
    - uses: actions/checkout@v2
    - name: credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: front end push 
      run: aws s3 sync ./frontend/dist s3://1a6lfd-rosie-jo.com