name: update website

on:
  push:
    branches:
    - main

jobs:
  backend_deploy:
    runs-on: ubuntu-latest

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2

    #   - name: Setup Terraform
    #     uses: hashicorp/setup-terraform@v1
    #     with:
    #       terraform_version: 1.4.6 # Replace with the desired Terraform version

    #   - name: Configure AWS Credentials
    #     uses: aws-actions/configure-aws-credentials@v1
    #     with:
    #       aws-region: us-east-1
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    #   - name: Initialize Terraform
    #     run: terraform init

    #   - name: Validate Terraform
    #     run: terraform validate

    #   - name: Plan Terraform
    #     run: terraform plan 

    #   - name: Plan Terraform test status
    #     if: steps.plan.outcome == 'failure'
    #     run: exit 1

    #   - name: Deploy Terraform
    #     run: terraform apply -auto-approve

  frontend_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: front end push 
      run: aws s3 sync ./frontend/dist s3://1a6lfd-rosie-jo.com